ci: fix async loss and speed
BaguaSys/bagua pull request #168
Opened 2021-08-27 11:20 UTC by wangraying

2021-08-30 10:19 UTC, wangraying commented on .buildkite/scripts/benchmark_master.sh
> +losses=(0.001763 0.001694 0.002583 0.001821 0.000010 0.004000)
These two values remain in the air

2021-08-31 01:15 UTC, NOBLES5E requested changes
gpu test seems crashed

2021-08-31 01:18 UTC, wangraying commented
> gpu test seems crashed

bagua-core needs to merge first

2021-08-31 01:31 UTC, NOBLES5E commented
> > gpu test seems crashed
> 
> bagua-core needs to merge first

Done. Try triggering test again :)

2021-09-15 11:11 UTC, wangraying commented
merge to https://github.com/BaguaSys/bagua/pull/185

2021-09-15 11:11 UTC, closed without merging