fix: auto installation for centos
BaguaSys/bagua pull request #66
Opened 2021-06-30 09:56 UTC by liuhatry

2021-06-30 21:46 UTC, NOBLES5E requested changes
see comments

2021-06-30 21:46 UTC, NOBLES5E commented on install.sh
> +python3 -m pip install bagua-core==0.2.2.dev18 -f https://repo.arrayfire.com/python/wheels/3.8.0/ -i https://pypi.org/simple
better with stable versions?

2021-07-01 03:58 UTC, liuhatry commented on install.sh
> +python3 -m pip install bagua-core==0.2.2.dev18 -f https://repo.arrayfire.com/python/wheels/3.8.0/ -i https://pypi.org/simple
done

2021-07-01 04:01 UTC, NOBLES5E commented on install.sh
> +    #scl enable devtoolset-8 bash
remove this line if not used

2021-07-01 04:01 UTC, NOBLES5E requested changes
see comments

2021-07-01 04:03 UTC, merged